---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'loveyourwater'


#Security setting for Member class
Member:
  extensions:
    - MemberExtension
  lock_out_after_incorrect_logins:
    5
  lock_out_delay_mins:
    60

Event:
  extensions:
   - EventExtension

SiteConfig:
  extensions:
   - SiteConfigExtension