---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'loveyourwater'


#Security setting for Member class
Member:
  extensions:
    - MemberExtension
  lock_out_after_incorrect_logins:
    4
  lock_out_delay_mins:
    60

Event:
  extensions:
   - EventExtension

SiteConfig:
  extensions:
   - SiteConfigExtension
TestSessionEnvironment:
  extensions:
    - LywTestSessionExtension
  database_templates_path: mysite/tests/fixtures/behat

TestSessionController:
  extensions:
    - LywTestSessionExtension
  database_templates_path: mysite/tests/fixtures/behat

LeafletField:
  map_options:
    tileLayer: '//{s}.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}.png'
    subdomains:
      - 'server'
      - 'services'
    attribution: 'ESRI, OpenStreetMap'
