<?php

class LearnVideo extends DataObject
{

    private static $db = [
        'Title' => 'Varchar(255)',
        'Description' => 'Text',
        'VideoID' => 'Varchar(11)',
        'SortField' => 'Int',
    ];

    private static $has_one = [
        'Link' => 'LearnPage',
    ];

    private static $default_sort = 'SortField ASC';

    public function getCMSFields()
    {
        $fields = new FieldList();

        $fields->push(TextField::create('Title'));
        $fields->push(TextareaField::create('Description'));
        $fields->push(YouTubeField::create('VideoID', 'YouTube URL'));

        return $fields;
    }

    public function onBeforeWrite()
    {
        // Set the auto-sort to be after all other existing documents.
        if (!$this->SortField) {
            $this->SortField = LearnVideo::get()->max('SortField') + 1;
        }

        parent::onBeforeWrite(); // TODO: Change the autogenerated stub
    }

}
